PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE recipes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      nama TEXT,
      kategori TEXT,
      gambar TEXT,
      bahan TEXT, -- disimpan dalam format JSON
      cara TEXT   -- disimpan dalam format JSON
    );
INSERT INTO recipes VALUES(25,'Garlic Butter Chicken 🍖🥘','makanan','src/asset/1744619895882-594524287-1744615766402-201519860-garlic.jpg','["Paha ayam 400 gr","Bawang putih 6 siung","Garam 1/2 sdt","Paprika powder 2 sdt (wajib)","Kaldu jamur 1/2 sdt","Lada","Unsalted butter 2 sdm","Cabe merah 2 pcs","Parsley 1 sdt"]','["Potong ayam dadu seukuran one bite","Marinasi ayam dengan garam, kaldu jamur, lada, dan paprika powder selama minimal 30 menit","Pan ayam sampai matang lalu masukkan butter sampai meleleh baru masukkan garlic","Masak sampai garlic muli kering, masukkan potongan cabai dan parsley dan masak hingga matang"]');
INSERT INTO recipes VALUES(26,'Chicken Katsu 🍛🍱','makanan','src/asset/1744620078064-31199039-1744552452640-135891583-katsu.jpg','["500 gr dada ayam fillet","1/4 sdt lada bubuk","1/2 sdt kaldu bubuk","1 butir telur","tepung panir","2 siung bawang putih halus","2 sdm margarin","3 siung bawang putih cincang","bawang bombai secukupnya","2 sdm saus sambel","2 sdm saos tomat","1 sdm saos tiram","1/2 sdm kecap manis","1/2 sdm cabe bubuk","100 ml air","1 sdm maizena yang dilarutkan dengan air"]','["sediakan ayam dada pilet , kemudian dibelah menjadi 2 bagian dengan tebal daging sama rata","oleskan dengan bawang putih, kaldu bubuk dan lada bubuk pada daging sambil dipijet dengan tangan lalu diamkan selama 10 menit","balur ayam dengan tepung terigu","balur ayam dengan tepung panir hingga permukaan daging tertutup merata","goreng ayam dengan minyak panas api kecil sambil di bolak balik","saos sambal dibuat dengan mencampurkan saos tomat, saos sambel dan lainnya, takaran sesuai dengan list bahan","tumis bawang putih cincang dan masukkan potongan bawang bombay kemudian masukkan saos yang sudah dicampurkan tadi","tambahkan larutan maizena","sajikan dengan sayur pelengkap seperti selada"]');
INSERT INTO recipes VALUES(27,'Sweet & Spicy Chicken 🍖🥙','makanan','src/asset/1744620126431-560222276-1744552505530-35110503-asampedasmanis.jpg','["1 sdt garam","1 sdt lada bubuk","1 butir telur","3 siung bawang putih","bawang bombay","saos tiram","saos indofood thailand","saos abc sambal","maizena","daun bawang","Cabai"]','["siapkan ayam dada yang dipotong dadu, kemudian masukkan 1 sdt garam, 1 sdt lada bubuk dan 1 butir telur kemudian aduk dan marinasi selama 10 menit","tambahkan tepung serbaguna dan ratakan","goreng ayam dengan minyak panas api sedang","oseng bawang putih, bawang bombay, potongan cabe, saos tiram, saos indofood thailand, kecap manis, saos sambal kemudian tambahkan air","tambahkan larutan maizena agar kental","tambahkan toping dengan potongan daun bawang"]');
INSERT INTO recipes VALUES(28,'Chicken Teriyaki 🧅🍚','makanan','src/asset/1744620227885-778741874-1744552546847-710318044-teriyaki.jpg','["ayam dada fillet","1 sdt garam","1 sdt lada bubuk","tepung ayam crispy","5 sdm tepung terigu","5 sdm tepung sajiku serbaguna","1 butir telur","3 siung bawang putih","Bawang","Kecap","Cabai"]','["Marinasi ayam dengan bawang putih cincang dan tambahkan 1 sdt garam dan 1 sdt lada putih bubuk kemudian diamkan selama 30 menit","Campurkan tepung ayam crispy, 5 sdm tepung terigu,dan 5 sdm tepung sajiku serbaguna","taburkan ayam ke tepung yang telah dicampurkan tadi","Goreng ayam dengan api sedang lalu tiriskan","Tumis bawang putih dengan margarin, kemudian masukkan bawang bombay dan cabai (optional)","Tambahkan saos teriyaki, kecap manis, saos sambal, dan saos tomat dan tambahkan air secukupnya kemudian masukkan ayam dan aduk hingga merata","Tambahkan larutan maizena agar kental"]');
INSERT INTO recipes VALUES(29,'Opor ayam putih 🍗🧄','makanan','src/asset/1744620281785-368636738-1744552612595-847415614-oporputih.jpg','["1/2 kg ayam yang telah dipotong kecil","daun salam","daun jeruk","batang serai","lengkuas","1 sdm lada putih bubuk, 1 sdm ketumbar, 1/2 sdt jinten, jahe 3 cm, 6 siung bawang putih, 6 siung bawang merah, 6 butir kemiri, 1 sdm garam kasar, santan, gula pasir, kaldu jamur, kacang panjang (optional), bawang goreng"]','["Rebus daun salam, jahe dan daun jeruk, kemudian masukkan ayam, rebus selama 20 menit","Ulek bumbu opor: 1 sdm lada putih, 1 sdm ketumbar, 1/2 sdt jinten, jahe 3 cm, 6 siung bawang putih, 6 siung bawang merah, 6 butir kemiri, 1 sdm garam kasar tumbuk semua bumbu hingga halus","Tumis bumbu yang sudah halus, tambahkan daun jeruk, daun salam , batang serau dan lengkuas, kemudian masukkan ayam yang sudah direbus","Tambahkan santan masak hingga mendidih","Masukkan kacang panjang (optional) bisa menambahkan sayuran lain sesuai selera","Tambahkan 1 sdm gula pasir dan 1 sdm kaldu jamur","Masak hingga air santan menyusut dan ayam matang","Tambahkan bawang goreng untuk toppingnya"]');
INSERT INTO recipes VALUES(30,'Ayam Koloke 🥦🍲','makanan','src/asset/1744620322275-328822351-1744552675373-856800284-koloke.jpg','["300g dada ayam, potong dadu","2 sdm tepung terigu","3 sdm tepung maizena","1 butir telur","1/2 sdt garam","1/2 sdt merica","Minyak untuk menggoreng","1/2 bawang bombay, iris","2 siung bawang putih, cincang","1 buah wortel, iris tipis","1/2 paprika merah, potong kotak","1/2 paprika hijau, potong kotak","3 sdm saus tomat","1 sdm saus tiram","1 sdt gula pasir","1/2 sdt garam","1/2 sdt merica","100ml air","1 sdt tepung maizena, larutkan dengan sedikit air"]','["Campurkan ayam dengan garam, merica, telur, tepung terigu, dan tepung maizena. Aduk rata.","Goreng ayam dalam minyak panas hingga kecoklatan dan matang. Angkat dan tiriskan.","Tumis bawang putih dan bawang bombay hingga harum.","Masukkan wortel, paprika merah, dan paprika hijau, tumis hingga agak layu.","Tambahkan saus tomat, saus tiram, gula, garam, dan merica. Aduk rata.","Tuang air dan biarkan mendidih.","Masukkan larutan maizena untuk mengentalkan saus, aduk hingga merata.","Masukkan ayam goreng ke dalam saus, aduk rata hingga ayam terlapisi saus.","Sajikan Ayam Koloke selagi hangat."]');
INSERT INTO recipes VALUES(31,'Spicy Aglio e Olio 🥢🌶️','makanan','src/asset/1744620374808-723102415-1744552748417-831392985-olio.jpg','["Fecctucine","4 siung bawang putih","Chile flakes","pasrley","Kecap","Bumbu lainnya"]','["Potong tipis bawang putih","Rebus fettucine dengan air yang diberi sedikit garam, rebus hingga pasta aldente","Tumis bawang dan masukkan chili flakes hingga harum","Masukkan fettucine lalu tambahkan dengan air sisa rebusan pasta tadi","Tambahkan kecap, dan bumbu lainnya","Taburkan parsley agar makin cantik","Aduk hingga merata dan matang"]');
INSERT INTO recipes VALUES(34,'Sweet Soy Sauce Chicken 🍗🍳','makanan','src/asset/1744700689423-500491378-1744552832513-212175158-kecap.jpg','["[\"Ayam yang telah dipotong kecil\",\"1 sdm kecap asin\",\"bawang bombay\",\"3 siung bawang putih\",\"3 sdm saos tiram\",\"8 sdm kecap manis (sesuai selera)\",\"Cabai (optional)\"]"]','["[\"Peras jeruk nipis lime keseluruh bagian ayam\",\"tambahkan 1 sdm kecap asin\",\"Tambahkan 1 sdm tepung terigu lalu ratakan\",\"Goreng ayam hingga kecokelatan\",\"tumis bawang bombay dan cincang bawang putih\",\"masukkan ayam yang telah digoreng dan tumis hingga matang\",\"Tambahkan saos tiram dan kecap manis\",\"Tambahkan cabai dan bawang bombay\",\"Aduk hingga merata dan matang\"]"]');
INSERT INTO recipes VALUES(36,'Fettucine Carbonara 🥢🍝','makanan','src/asset/1744877417071-879978513-gambar-pasta.jpg','["2 telur omega","topping daging (smoke beef/ayam)","80 gram keju cheddar","1/4 sdt chili flakes (optional)","1/4 sdt kaldu jamur","1/4 sdt pasrley kering","1 sdt garam","100 gr Fettucine","650 ml air","brokoli","minyak goreng"]','["rebus fettucine dengan 650 ml air dan tambahkan 1 sdt garam, rebus selama 7-10 menit (rebus pasta hingga aldente)","Air sisa rebusan disisihkan sebanyak 80 ml air (digunakan untuk menumis)","potong daging smoke beef/ daging ayam / daging yang lain sesuai selera","kemudian buat saosnya di wadah terpisah masukkan 2 kuning telur jenis omega, 80 gram keju cheddar parut, 1/4 sdt chili flakes (opsional), 1/4 sdt kaldu jamur, 1/4 sdt pasrley kering dan campur dengan air sisa rebusan","tumis toping daging hingga harum kemudian masukkan campurang telur dan keju secara perlahan hingga keju larut","tambahkan sayur brokoli sebagai pelengkap dan taburkan parsley"]');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('recipes',36);
COMMIT;
